#ifndef ASTRA_CONFIG_MQH
#define ASTRA_CONFIG_MQH
#property strict
#define ASTRA_VERSION "2.200"
#define ASTRA_BUILD_ID "85E6DA1C-5EF8-457A-BDDA-DC3C5858C277"
#define ASTRA_DEFAULT_MAGIC 20260801
#define ASTRA_SCANNER_MIN_BARS 200
#define ASTRA_STRUCTURE_LOOKBACK_BARS 100
#define ASTRA_STRUCTURE_FRACTAL_WIDTH 2
#define ASTRA_MIN_CONFLUENCE 15.0
#define ASTRA_REQUIRE_BOS_FOR_ENTRY false
#define ASTRA_MAX_SPREAD_POINTS 30
#define ASTRA_MAX_AGGREGATE_RISK_PERCENT_DEFAULT 4.00
#define ASTRA_CONFLUENCE_VALID_QUALITY_DEFAULT 0.60
#define ASTRA_CONFLUENCE_NEUTRAL_QUALITY_DEFAULT 0.35
#define ASTRA_DEFAULT_SLIPPAGE 20
#define ASTRA_ML_MAX_WEIGHT 15.0
#define ASTRA_BO_VALID_CANDLES 5
#define ASTRA_BO_EXPIRY_CANDLES 2
#define ASTRA_BO_MARTINGALE_A 1
#define ASTRA_BO_MARTINGALE_B 1
#define ASTRA_BO_MARTINGALE_C 0
#define ASTRA_MIN_CONFIDENCE_DEFAULT 0.55
#define ASTRA_MIN_CONSENSUS_DEFAULT 25.0
#define ASTRA_MIN_PREDICTION_CONFIDENCE_DEFAULT 0.40
#define ASTRA_MIN_RISK_REWARD_DEFAULT 1.50
#define ASTRA_DEFAULT_RISK_PERCENT 2.00
#define ASTRA_DEFAULT_MARGIN_BUFFER 0.80
#define ASTRA_BTC_MODIFIER_ENABLED false
#define ASTRA_BTC_MAX_MODIFIER 0.03
#endif
