#ifndef ASTRA_TYPES_MQH
#define ASTRA_TYPES_MQH
#property strict

enum ENUM_BIAS { BIAS_BULLISH=0, BIAS_BEARISH=1, BIAS_NEUTRAL=2 };
enum ENUM_DECISION { DECISION_NONE=0, DECISION_BUY=1, DECISION_SELL=2 };
enum ENUM_REGIME { REGIME_EXPANSION=0, REGIME_CONTRACTION=1, REGIME_RANGE=2, REGIME_TRANSITION=3 };
enum ENUM_PRICE_LOCATION
{
   PRICE_LOCATION_UNKNOWN = 0,
   PRICE_LOCATION_NEAR_SUPPORT,
   PRICE_LOCATION_NEAR_RESISTANCE,
   PRICE_LOCATION_MID_RANGE,
   PRICE_LOCATION_BREAKING_SUPPORT,
   PRICE_LOCATION_BREAKING_RESISTANCE
};
enum ENUM_WYCKOFF_PHASE { WYCKOFF_NONE=0, WYCKOFF_ACCUMULATION=1, WYCKOFF_SOS=2, WYCKOFF_DISTRIBUTION=3, WYCKOFF_SOW=4 };
enum ENUM_ELLIOTT_WAVE { ELLIOTT_NONE=0, ELLIOTT_IMPULSE_1=1, ELLIOTT_IMPULSE_3=2, ELLIOTT_IMPULSE_5=3, ELLIOTT_CORRECTIVE_A=4, ELLIOTT_CORRECTIVE_B=5, ELLIOTT_CORRECTIVE_C=6, ELLIOTT_WAVE_X=7 };
enum ENUM_LAYER_STATE { LAYER_INVALID=0, LAYER_NEUTRAL=1, LAYER_VALID=2 };
enum ENUM_OPPORTUNITY_GRADE { GRADE_NO_TRADE=0, GRADE_C=1, GRADE_B=2, GRADE_A=3, GRADE_A_PLUS=4 };
enum ENUM_RISK_LEVEL { RISK_LOW=0, RISK_MEDIUM=1, RISK_HIGH=2, RISK_EXTREME=3 };
enum ENUM_ASTRA_DATA_QUALITY { ASTRA_DATA_UNKNOWN=0, ASTRA_DATA_GOOD=1, ASTRA_DATA_INVALID=2 };
enum ENUM_ASTRA_BLOCK_REASON {
   ASTRA_BLOCK_NONE=0, ASTRA_BLOCK_NO_DECISION, ASTRA_BLOCK_INVALID_DATA, ASTRA_BLOCK_INVALID_RISK,
   ASTRA_BLOCK_MARGIN_INSUFFICIENT, ASTRA_BLOCK_SPREAD, ASTRA_BLOCK_SESSION, ASTRA_BLOCK_MARKET_CLOSED,
   ASTRA_BLOCK_SYMBOL, ASTRA_BLOCK_TRADING_DISABLED, ASTRA_BLOCK_POSITION_ALREADY_OPEN, ASTRA_BLOCK_COOLDOWN_ACTIVE,
   ASTRA_BLOCK_NEWS, ASTRA_BLOCK_EXPOSURE_LIMIT, ASTRA_BLOCK_UNPROTECTED_POSITION
};
enum ENUM_TRAFFIC_LIGHT { TRAFFIC_RED=0, TRAFFIC_YELLOW=1, TRAFFIC_GREEN=2, TRAFFIC_STRONG_GREEN=3 };
enum ENUM_TRAFFIC_DIRECTION { TRAFFIC_NONE=0, TRAFFIC_BULLISH=1, TRAFFIC_BEARISH=2 };
enum ENUM_ASTRA_MTF_STATE { ASTRA_MTF_NEUTRAL=0, ASTRA_MTF_ALIGNED=1, ASTRA_MTF_CONFLICT=2 };
#endif
